on: push

jobs:
  curl:
    runs-on: ubuntu-latest
    steps:
      - name: Download file with curl
        run: |
          curl -L https://download.sysinternals.com/files/ProcessExplorer.zip -o file/ProcessExplorer.zip

      - name: Setup Rclone
        uses: AnimMouse/setup-rclone@v1
        with:
          rclone_config: ${{ secrets.RCLONE_CONF }}

      - name: Upload to rclone remote
        run: |
          rclone copy ./file BDoDrive:Here/file --progress
