name: Convert to HEVC using x265 CLI

on:
  workflow_dispatch:

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install static ffmpeg with libfdk_aac
  run: |
    curl -L https://johnvansickle.com/ffmpeg/releases/ffmpeg-release-amd64-static.tar.xz -o ffmpeg.tar.xz
    tar -xf ffmpeg.tar.xz
    sudo mv ffmpeg-*-amd64-static/ffmpeg /usr/local/bin/
    sudo chmod +x /usr/local/bin/ffmpeg

      - name: Setup Rclone
        uses: AnimMouse/setup-rclone@v1
        with:
          rclone_config: ${{ secrets.RCLONE_CONFIG }}

      - name: Download videos from rclone remote
        run: |
          mkdir -p input
          rclone copy DBOX:DL ./input --include "*.mp4" --include "*.mkv" --include "*.avi" --include "*.mov" --include "*.webm" --progress

      - name: Convert videos using FFmpeg piped to x265
        run: |
          mkdir -p output
          for f in ./input/*; do
            filename=$(basename "$f")
            name="${filename%.*}"

            # Encode video via pipe to x265
            ffmpeg -i "$f" -vf fps=24 -map 0 -c:a libfdk_aac -profile:a aac_he_v2 -b:a 25k -c:s copy -f yuv4mpegpipe -pix_fmt yuv420p -strict -1 - | \ x265 - --frame-threads 16 --crf 37 --deblock=0:0 --pools none --log-level 2 --output-depth 8 --y4m --profile main10 --high-tier --min-cu-size 8 --ctu 64 --qg-size 32 --no-opt-cu-delta-qp --tu-intra-depth 1 --tu-inter-depth 1 --limit-tu 0 --max-tu-size 32 --me hex --subme 2 --merange 57 --no-limit-modes --no-rect --no-amp --max-merge 3 --early-skip --rskip 1 --rdpenalty 0 --no-tskip --strong-intra-smoothing --no-constrained-intra --open-gop --opt-ref-list-length-pps --keyint 250 --min-keyint 23 --bframes 4 --no-weightb --bframe-bias 0 --b-adapt 2 --b-pyramid --ref 3 --weightp --rc-lookahead 20 --slices 1 --lookahead-threads 0 --scenecut 40 --scenecut-bias 5 --qpstep 4 --qpmin 0 --qpmax 69 --opt-qp-pps --no-rc-grain --cbqpoffs -2 --crqpoffs 0 --ipratio 1.4 --pbratio 1.3 --nr-intra 0 --nr-inter 0 --rd 4 --no-fast-intra --no-ssim-rd --no-rd-refine --psy-rd 0.40 --no-rdoq-level --no-psy-rdoq --signhide --qcomp 0.6 --no-aq-motion --aq-mode 2 --aq-strength 0.60 --cutree --no-cu-lossless --vbv-maxrate 0 --vbv-bufsize 0 --vbv-init 0.9 --no-hrd --no-aud --info --sao --no-sao-non-deblock --no-temporal-layers --log2-max-poc-lsb 8 --no-psnr --no-ssim --no-interlace --range limited --colorprim bt709 --transfer bt709 --colormatrix bt709 --max-cll "0,0" --hdr --temporal-mvp  --no-b-intra --lookahead-slices 0 --limit-refs 0 --no-repeat-headers -o "output/${name}.hevc" -

            # Remux everything back into mp4 with metadata and subtitles
            ffmpeg -i "$f" -i "output/${name}.hevc" -map 0 -map -0:v -map 1:v -c copy "output/${name}_x265.mp4"

            # Clean intermediate .hevc
            rm "output/${name}.hevc"
          done

      - name: Upload encoded videos to rclone remote
        run: |
          rclone copy ./output BDoDrive:Here/Hevc --progress
