name: Convert to HEVC using x265 CLI

on:
  workflow_dispatch:

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install FFmpeg and x265
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg x265

      - name: Setup Rclone
        uses: AnimMouse/setup-rclone@v1
        with:
          rclone_config: ${{ secrets.RCLONE_CONFIG }}

      - name: Download videos from rclone remote
        run: |
          mkdir -p input
          rclone copy DBOX:DL ./input --include "*.mp4" --include "*.mkv" --include "*.avi" --include "*.mov" --include "*.webm" --progress

      - name: Convert videos using FFmpeg piped to x265
        run: |
          mkdir -p output
          for f in ./input/*; do
            filename=$(basename "$f")
            name="${filename%.*}"

            # Encode video via pipe to x265
            ffmpeg -i "$f" -vf fps=24 -map 0 -c:a aac -b:a 128k -c:s copy -f yuv4mpegpipe -pix_fmt yuv420p -strict -1 - | \
            x265 --y4m --crf 28 --preset slow -o "output/${name}.hevc" -

            # Remux everything back into mp4 with metadata and subtitles
            ffmpeg -i "$f" -i "output/${name}.hevc" -map 0 -map -0:v -map 1:v -c copy "output/${name}_x265.mp4"

            # Clean intermediate .hevc
            rm "output/${name}.hevc"
          done

      - name: Upload encoded videos to rclone remote
        run: |
          rclone copy ./output BDoDrive:Here/Hevc --progress
