name: Convert All Videos in Remote Folder

on:
  workflow_dispatch:

jobs:
  list-files:
    runs-on: ubuntu-latest
    outputs:
      files: ${{ steps.set-matrix.outputs.files }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Rclone
        uses: AnimMouse/setup-rclone@v1
        with:
          rclone_config: ${{ secrets.RCLONE_CONF }}

      - name: List video files from remote
        id: set-matrix
        run: |
          mkdir -p input
          rclone lsf "BDoDrive:YT/Modelling/Vid" --include "*.mp4" --include "*.mkv" --include "*.webm" --files-only > files.txt
          files=$(jq -R -s -c 'split("\n") | map(select(length > 0))' files.txt)
          echo "files=$files" >> "$GITHUB_OUTPUT"

  convert:
    needs: list-files
    runs-on: ubuntu-latest
    strategy:
      matrix:
        file: ${{ fromJson(needs.list-files.outputs.files) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Rclone
        uses: AnimMouse/setup-rclone@v1
        with:
          rclone_config: ${{ secrets.RCLONE_CONF }}

      - name: Install tools (ffmpeg, x265, fdkaac)
        run: |
          sudo apt-get update
          curl -L https://johnvansickle.com/ffmpeg/releases/ffmpeg-release-amd64-static.tar.xz -o ffmpeg.tar.xz
          tar -xf ffmpeg.tar.xz
          sudo mv ffmpeg-*-amd64-static/ffmpeg /usr/local/bin/
          sudo apt-get install x265
          sudo apt install ffmpeg
          curl -L -o fdkaac.tar.gz https://github.com/N0rms1nk/vomiu/releases/download/v1.0.0/fdkaac_static.tar.gz
          tar -xzf fdkaac.tar.gz
          chmod +x fdkaac
          sudo mv fdkaac /usr/local/bin/fdkaac

      - name: Download video
        run: |
          mkdir -p input
          rclone copy "BDoDrive:YT/Modelling/Vid/${{ matrix.file }}" ./input/

      - name: Make script executable and run
        run: |
          chmod +x scripts/convert_video.sh
          ./scripts/convert_video.sh "./input/${{ matrix.file }}"

      - name: Upload output
        run: |
          rclone copy ./output BDoDrive:Here/YT/Modelling --progress
